version: "3"
services:
  prisma:
    network_mode: "host"
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mongo
            uri: 'mongodb://localhost:27017'
  client:
    network_mode: "host"
    build:
      context: "./"
      dockerfile: "./client.Dockerfile"
  server:
    network_mode: "host"
    build:
      context: "./"
      dockerfile: "./server.Dockerfile"
  prisma_dev:
    image: prismagraphql/prisma:1.34
    restart: always
    network_mode: "host"
    ports:
      - "5566:5566"
    environment:
      PRISMA_CONFIG: |
        port: 5566
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          sandbox:
            connector: mongo
            uri: 'mongodb://localhost:27017'
